### ISSUE TITLE
Add organization IDs of the other datasets

### ISSUE THREAD

**Issue by romain-fontugne** [InetIntel/Dataset-AS-to-Organization-Mapping#1]
In order to map this dataset with the data provided by peeringDB and CAIDA we currently have to rely on the organization names. This may become a problem if multiple organizations have the same name or if the names change.

That would be great if this dataset could give the specific organization ID it refers to in the other datasets (e.g. org_id from peeringdb), so we can have a better way to do one-to-one mapping across datasets.

**Comment by zhiyichenGT** [comment]
Thanks Romain. I have added (1) a 'PDB.org_id' column for each AS, and (2) an 'org_id' field in 'Reference Orgs' if the source is PDB. Please let me know if you have further questions.

**Comment by romain-fontugne** [comment]
Thanks, this is great!
